# This file may be used to create a Python/conda environment using conda itself or mamba (faster):
#   mamba remove --name ConceptualDesign --all
#   mamba env create --name ConceptualDesign --file environment.yml

name: ConceptualDesign

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.10
  - jupyter
  - matplotlib
  - numpy
  - scipy
  # - sympy
  # - numpy-stl
  - trimesh
  - networkx    # needed by trimesh but dependency not set
  - pyglet      # needed by trimesh but dependency not set
  - lxml        # needed by trimesh but dependency not set
  - rtree       # needed by trimesh but dependency not set
  - pycollada   # if you want trimesh to read Collada files
  - pyvista
  # - sympy_plot_backends[all]

# pip install pygltflib   # alternative way of reading glTF files


## Add environment variables to this conda env:
# conda env config vars set PYTHONPATH="${HOME}/miniconda3/envs/Conceptual/lib/python3.10/site-packages:${HOME}/Teaching/ConceptualDesign/Packages"
## List them using:
# conda env config vars list

